# fly.toml app configuration file generated for reactivities-serena on 2023-12-06T16:20:01-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-serena"
primary_region = "sea"

[build]
  image = "serenadev/reactivities:latest"

[env]
  ASPNETCORE_URLS ="http://+:8080"
  Cloudinary__CloudName="do43psomf"
  Cloudinary__ApiKey="952664852719853"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
